# Generated by Django 5.1.7 on 2025-04-08 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('gender', models.CharField(max_length=10)),
                ('phone', models.IntegerField()),
                ('aadhar', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=32)),
                ('acc', models.BigIntegerField(unique=True)),
                ('pin', models.IntegerField(default=0)),
                ('bal', models.DecimalField(decimal_places=2, default=1000, max_digits=5)),
            ],
        ),
    ]
